//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigData.Analysis.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BadInfo
    {
        public int Id { get; set; }
        public string BadClass { get; set; }
        public long Nums { get; set; }
        public string BadExplain { get; set; }
        public string Analysis { get; set; }
        public string ReasonClass { get; set; }
        public string Date { get; set; }
        public string RepairMan { get; set; }
        public int MachineOutputId { get; set; }
    
        public virtual MachineOutput MachineOutput { get; set; }
    }
}
